spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        forma_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
